@startuml
title Caso de Uso 2 - Cancelar turno exitoso

|Paciente|
start
:Contactar a la secretaria;
:Proveer identificación y solicitar cancelación;

|Secretaria|
:Iniciar sesión en SistemaTurnosMedicos;

|SistemaTurnosMedicos|
:Validar si el paciente existe en el sistema;

if (¿El paciente existe en el sistema?) then (sí)

  :Consultar turnos activos del paciente;

  |SistemaTurnosMedicos|
  :Buscar turnos activos por paciente;
  :Devolver listado de turnos activos;

  |Secretaria|
  if (¿Existe el turno que desea cancelar?) then (sí)

    |Paciente|
    :Confirmar el turno a cancelar;

    |Secretaria|
    :Confirmar solicitud de cancelación;

    |SistemaTurnosMedicos|
    :Cancelar turno en la agenda;
    :Liberar disponibilidad de la franja horaria;
    :Actualizar estado del turno como cancelado;
    :Registrar cambio en historial de modificaciones;
    :Notificar al médico sobre la cancelación del turno;

    |Secretaria|
      :Notificar cancelación al paciente;

    |Paciente|
    :Recibir confirmación de cancelación;
    stop

  else (no)

    |Secretaria|
    :Informar que no hay un turno activo para ese paciente;
    :Finalizar atención sin cancelar turno;
    end

  endif

  else (no)

  |Secretaria|
  :Informar al paciente que no está registrado;
  end

endif

@enduml