@startuml

interface EstrategiaDisponibilidad {
  + obtenerFranjasDisponibles(fecha: Date): List<Time>
}

class DisponibilidadMedicoGeneral implements EstrategiaDisponibilidad {
  + obtenerFranjasDisponibles(fecha: Date): List<Time>
}

class DisponibilidadQuirofano implements EstrategiaDisponibilidad {
  + obtenerFranjasDisponibles(fecha: Date): List<Time>
}

class Doctor {
  - estrategia: EstrategiaDisponibilidad
  + setEstrategia(estrategia: EstrategiaDisponibilidad)
  + consultarDisponibilidad(fecha: Date): List<Time>
}

Doctor "1" --> "1" EstrategiaDisponibilidad : usa >

@enduml