@startuml
left to right direction
actor Paciente
actor Secretaria

usecase "Registrar paciente" as UC1
usecase "Ingresar datos" as UC2
usecase "Validar datos" as UC3
usecase "Almacenar paciente" as UC4

Paciente -- UC1
Secretaria -- UC1

UC1 ..> UC2 : <<include>>
UC1 ..> UC3 : <<include>>
UC1 ..> UC4 : <<include>>
@enduml