@startuml

abstract class Doctor {
  + verAgenda(): void
}

class Cardiologo extends Doctor {
  + verAgenda(): void
}

class Pediatra extends Doctor {
  + verAgenda(): void
}

class Traumatologo extends Doctor {
  + verAgenda(): void
}

@enduml
