@startuml
left to right direction

actor Paciente
actor Secretaria

usecase "Registrar llegada del paciente" as UC1
usecase "Verificar turno" as UC2
usecase "Marcar en espera" as UC3

Paciente -- UC1
Secretaria -- UC1

UC1 ..> UC2 : <<include>>
UC1 ..> UC3 : <<include>>

@enduml