@startuml
left to right direction

actor Paciente
actor Secretaria

rectangle "Sistema de Turnos Médicos" {
    usecase "Solicitar turno" as UC1
    usecase "Verificar disponibilidad" as UC2
    usecase "Registrar turno" as UC3
    usecase "Notificar asignación al paciente" as UC4
}

Paciente -- UC1
Secretaria -- UC1

UC1 ..> UC2 : <<include>>
UC1 ..> UC3 : <<include>>
UC1 ..> UC4 : <<include>>
@enduml
